# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20170928_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addedby', to='wishlist.User')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdby', to='wishlist.User')),
            ],
        ),
    ]
