# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='addedby',
        ),
        migrations.AddField(
            model_name='item',
            name='addedby',
            field=models.ManyToManyField(related_name='addedby', to='wishlist.User'),
        ),
    ]
