# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_auto_20170928_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addedby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='addedby',
        ),
        migrations.AddField(
            model_name='addedby',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemadded', to='wishlist.Item'),
        ),
        migrations.AddField(
            model_name='addedby',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addedby', to='wishlist.User'),
        ),
    ]
